{
    825: {
        b'type': b'shell',
        b'tunnel_local': b'172.28.128.2:4444',
        b'tunnel_peer': b'172.28.128.3:46533',
        b'via_exploit': b'exploit/unix/irc/unreal_ircd_3281_backdoor',
        b'via_payload': b'payload/cmd/unix/reverse',
        b'desc': b'Command shell',
        b'info': b'',
        b'workspace': b'default',
        b'session_host': b'172.28.128.3',
        b'session_port': 6697,
        b'target_host': b'172.28.128.3',
        b'username': b'omamba',
        b'uuid': b'dtpic2un',
        b'exploit_uuid': b'qrswq03l',
        b'routes': b'', 
        b'arch': b'cmd'
    }, 
    826: {
        b'type': b'shell',
        b'tunnel_local': b'172.28.128.2:4444',
        b'tunnel_peer': b'172.28.128.3:46537',
        b'via_exploit': b'exploit/unix/irc/unreal_ircd_3281_backdoor',
        b'via_payload': b'payload/cmd/unix/reverse',
        b'desc': b'Command shell',
        b'info': b'',
        b'workspace': b'default',
        b'session_host': b'172.28.128.3',
        b'session_port': 6697,
        b'target_host': b'172.28.128.3',
        b'username': b'omamba',
        b'uuid': b'mlxmaphm',
        b'exploit_uuid': b'gzmdvw34',
        b'routes': b'',
        b'arch': b'cmd'
    }, 
    827: {
        b'type': b'shell',
        b'tunnel_local': b'172.28.128.2:4444',
        b'tunnel_peer': b'172.28.128.3:46551',
        b'via_exploit': b'exploit/unix/irc/unreal_ircd_3281_backdoor',
        b'via_payload': b'payload/cmd/unix/reverse',
        b'desc': b'Command shell',
        b'info': b'',
        b'workspace': b'default',
        b'session_host': b'172.28.128.3',
        b'session_port': 6697,
        b'target_host': b'172.28.128.3',
        b'username': b'omamba',
        b'uuid': b'6wgto6pp',
        b'exploit_uuid': b'2p7ldjhg',
        b'routes': b'',
        b'arch': b'cmd'
    }
}